namespace: development

resources:
  - ../../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: nginx-ingress
    path: patch.yaml

commonLabels:
  app: nginx-ingress
  app.kubernetes.io/name: nginx-ingress
  app.kubernetes.io/part-of: nginx-ingress
  app.kubernetes.io/managed-by: kustomize
